import type { HTMLAttributes, ReactNode } from "react";

import { classNames } from "../../utils/classNames";

interface GeminiLabelProps extends HTMLAttributes<HTMLSpanElement> {
  children?: ReactNode;
}

export function GeminiLabel({
  children = "Generated by Gemini",
  className,
  ...props
}: GeminiLabelProps) {
  return (
    <span className={classNames("gemini-label", className)} {...props}>
      <span aria-hidden="true">✨</span>
      {children}
    </span>
  );
}
